/**
 * Column type markers used by schema inference for select / insert / update shapes.
 */
export type ColumnType<Select, Insert = Select, Update = Select> = {
  readonly __select__: Select;
  readonly __insert__: Insert;
  readonly __update__: Update;
};

/** Column generated by the database (or application defaults); optional on insert. */
export type Generated<T> = ColumnType<T, T | undefined, T>;

type SelectType<T> = T extends ColumnType<infer S, any, any> ? S : T;
type InsertType<T> = T extends ColumnType<any, infer I, any> ? I : T;
type UpdateType<T> = T extends ColumnType<any, any, infer U> ? U : T;

/** Row shape returned by SELECT queries. */
export type Selectable<R> = {
  [K in keyof R]: SelectType<R[K]>;
};

type IfNeverThenElseOrUnknown<T, WhenNever, WhenElse> = [T] extends [never] ? WhenNever : WhenElse;

/** Row shape accepted by INSERT. Generated / defaulted columns are optional. */
export type Insertable<R> = {
  [
    K in keyof R as IfNeverThenElseOrUnknown<
      InsertType<R[K]>,
      never,
      undefined extends InsertType<R[K]> ? K : never
    >
  ]?: Exclude<InsertType<R[K]>, undefined>;
} & {
  [
    K in keyof R as IfNeverThenElseOrUnknown<
      InsertType<R[K]>,
      never,
      undefined extends InsertType<R[K]> ? never : K
    >
  ]: InsertType<R[K]>;
};

/** Partial row shape accepted by UPDATE. */
export type Updateable<R> = {
  [K in keyof R as IfNeverThenElseOrUnknown<UpdateType<R[K]>, never, K>]?: UpdateType<R[K]>;
};
